"use client";

import { useEffect, useState } from "react";
import { doc, getDoc, serverTimestamp, updateDoc } from "firebase/firestore";
import { useParams, useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { Comments } from "@/components/comments";
import { RecordDetailShell, RecordProperties, RecordProperty } from "@/components/record-detail-shell";
import { db } from "@/lib/firebase";

type Task = { title: string; description: string; status: string; priority: string; dueDate?: Date; createdAt?: Date; updatedAt?: Date; workspaceId: string };
export default function TaskDetailPage() {
  const { workspaceId, taskId } = useParams<{ workspaceId: string; taskId: string }>(); const router = useRouter(); const { firebaseUser, profile, loading: authLoading } = useAuth(); const [task, setTask] = useState<Task | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (!authLoading && !firebaseUser) router.replace("/login"); }, [authLoading, firebaseUser, router]);
  useEffect(() => { if (!firebaseUser || !profile) return; getDoc(doc(db, "tasks", taskId)).then((snapshot) => { const data = snapshot.data(); if (!data || data.workspaceId !== workspaceId) throw new Error("not found"); setTask({ title: data.title || "Untitled task", description: data.description || "", status: data.status || "todo", priority: data.priority || "medium", workspaceId: data.workspaceId, dueDate: data.dueDate?.toDate(), createdAt: data.createdAt?.toDate(), updatedAt: data.updatedAt?.toDate() }); }).catch(() => setError("Task could not be found.")); }, [firebaseUser, profile, taskId, workspaceId]);
  async function update(values: Partial<Task>) { if (!task) return; const next = { ...task, ...values }; setTask(next); try { await updateDoc(doc(db, "tasks", taskId), { ...values, updatedAt: serverTimestamp() }); } catch { setTask(task); setError("Task changes could not be saved."); } }
  if (authLoading || (!task && !error)) return <main className="grid min-h-screen place-items-center text-sm text-[#787774]">Loading task…</main>; if (!firebaseUser || !profile || !task) return <main className="grid min-h-screen place-items-center text-sm text-red-700">{error}</main>;
  return <RecordDetailShell backHref={`/workspaces/${workspaceId}/tasks`} backLabel="Tasks"><input aria-label="Task title" value={task.title} onChange={(event) => setTask({ ...task, title: event.target.value })} onBlur={(event) => update({ title: event.target.value.trim() || "Untitled task" })} className="mt-9 w-full bg-transparent text-4xl font-semibold tracking-[-0.03em] outline-none" /><RecordProperties><RecordProperty label="Status"><select aria-label="Task status" value={task.status} onChange={(event) => update({ status: event.target.value })} className="rounded bg-[#f1f1ef] px-2 py-1"><option value="todo">Not started</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="done">Done</option></select></RecordProperty><RecordProperty label="Priority"><select aria-label="Task priority" value={task.priority} onChange={(event) => update({ priority: event.target.value })} className="rounded bg-[#f1f1ef] px-2 py-1"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></RecordProperty><RecordProperty label="Due date">{task.dueDate?.toLocaleDateString() || "Empty"}</RecordProperty><RecordProperty label="Last edited">{task.updatedAt?.toLocaleString() || "—"}</RecordProperty></RecordProperties><Comments workspaceId={workspaceId} entityType="task" entityId={taskId} /><section className="mt-8 border-t border-black/[0.08] pt-5"><h2 className="text-base font-medium">Details</h2><textarea aria-label="Task description" value={task.description} onChange={(event) => setTask({ ...task, description: event.target.value })} onBlur={(event) => update({ description: event.target.value })} placeholder="Add a description…" className="mt-3 min-h-40 w-full resize-y bg-transparent text-sm leading-7 outline-none placeholder:text-[#9b9a97]" /></section></RecordDetailShell>;
}
