"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { addDoc, collection, onSnapshot, query, serverTimestamp, where } from "firebase/firestore";
import { useParams, useRouter } from "next/navigation";
import Sidebar from "@/components/sidebar";
import { useAuth } from "@/components/auth-provider";
import { db } from "@/lib/firebase";

type Meeting = { id: string; title: string; scheduledAt?: Date; updatedAt?: Date };
export default function MeetingsPage() { const { workspaceId } = useParams<{ workspaceId: string }>(); const router = useRouter(); const { firebaseUser, profile, loading } = useAuth(); const [meetings, setMeetings] = useState<Meeting[]>([]); const [creating, setCreating] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!loading && !firebaseUser) router.replace("/login"); }, [loading, firebaseUser, router]);
  useEffect(() => { if (!firebaseUser || !profile) return; return onSnapshot(query(collection(db, "meetings"), where("workspaceId", "==", workspaceId)), (snapshot) => setMeetings(snapshot.docs.map((item) => ({ id: item.id, title: item.data().title || "Untitled meeting", scheduledAt: item.data().scheduledAt?.toDate(), updatedAt: item.data().updatedAt?.toDate() })).sort((a, b) => (b.updatedAt?.getTime() || 0) - (a.updatedAt?.getTime() || 0))), (listenerError) => { console.error("Failed to load meetings:", listenerError); setError("Meetings could not be loaded."); }); }, [firebaseUser, profile, workspaceId]);
  async function createMeeting() { if (!firebaseUser || creating) return; try { setCreating(true); const ref = await addDoc(collection(db, "meetings"), { title: "Untitled meeting", workspaceId, createdBy: firebaseUser.uid, transcript: "", notes: "", actionItems: "", createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); router.push(`/workspaces/${workspaceId}/meetings/${ref.id}`); } catch (createError) { console.error("Failed to create meeting:", createError); setError("Meeting could not be created."); } finally { setCreating(false); } }
  if (loading) return <main className="grid min-h-screen place-items-center">Loading…</main>; if (!firebaseUser || !profile) return null;
  return <main className="flex min-h-screen bg-[var(--background)]"><Sidebar /><section className="proveit-content"><div className="proveit-content-inner max-w-5xl"><Link href={`/workspaces/${workspaceId}`} className="proveit-back-link px-1">← Back to workspace</Link><div className="proveit-page-header mb-8"><div><p className="proveit-label">MEETINGS</p><h1 className="proveit-page-title mt-1">Meetings</h1><p className="mt-3 text-sm text-[var(--muted)]">Capture transcripts, notes, and action items.</p></div><button onClick={createMeeting} disabled={creating} className="proveit-primary-button disabled:cursor-not-allowed disabled:opacity-50">{creating ? "Creating…" : "New meeting"}</button></div>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<div className="proveit-list">{meetings.map((meeting) => <Link key={meeting.id} href={`/workspaces/${workspaceId}/meetings/${meeting.id}`} className="proveit-list-row flex items-center gap-3 border-b border-black/[0.08] px-5 py-4 last:border-0"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[var(--sidebar)]">◷</span><div><p className="text-sm font-medium">{meeting.title}</p><p className="mt-0.5 text-xs text-[var(--subtle)]">{meeting.scheduledAt?.toLocaleString() || meeting.updatedAt?.toLocaleString() || "New meeting"}</p></div></Link>)}{meetings.length === 0 && <p className="px-5 py-12 text-sm text-[var(--muted)]">No meetings yet. Create a meeting or upload a recording.</p>}</div></div></section></main>;
}
