"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { doc, getDoc, serverTimestamp, updateDoc } from "firebase/firestore";
import { useParams, useRouter } from "next/navigation";
import Sidebar from "@/components/sidebar";
import { useAuth } from "@/components/auth-provider";
import { db } from "@/lib/firebase";
import { Comments } from "@/components/comments";

export default function MeetingDetailPage() { const { workspaceId, meetingId } = useParams<{ workspaceId: string; meetingId: string }>(); const router = useRouter(); const { firebaseUser, profile, loading: authLoading } = useAuth(); const [title, setTitle] = useState(""); const [transcript, setTranscript] = useState(""); const [notes, setNotes] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [fileName, setFileName] = useState(""); const fileInput = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!authLoading && !firebaseUser) router.replace("/login"); }, [authLoading, firebaseUser, router]);
  useEffect(() => { if (!firebaseUser || !profile) return; getDoc(doc(db, "meetings", meetingId)).then((snapshot) => { if (!snapshot.exists() || snapshot.data().workspaceId !== workspaceId) { setError("Meeting could not be found."); return; } const value = snapshot.data(); setTitle(value.title || "Untitled meeting"); setTranscript(value.transcript || ""); setNotes(value.notes || ""); }).catch((loadError) => { console.error("Failed to load meeting:", loadError); setError("Meeting could not be loaded."); }).finally(() => setLoading(false)); }, [firebaseUser, profile, meetingId, workspaceId]);
  async function save() { try { setSaving(true); setError(""); await updateDoc(doc(db, "meetings", meetingId), { title: title.trim() || "Untitled meeting", transcript, notes, updatedAt: serverTimestamp() }); } catch (saveError) { console.error("Failed to save meeting:", saveError); setError("Meeting changes could not be saved."); } finally { setSaving(false); } }
  async function copyTranscript() { try { await navigator.clipboard.writeText(transcript); } catch (copyError) { console.error("Failed to copy transcript:", copyError); setError("Transcript could not be copied."); } }
  if (authLoading || loading) return <main className="grid min-h-screen place-items-center">Loading meeting…</main>; if (!firebaseUser || !profile) return null;
  return <main className="flex min-h-screen bg-[#fbfbfa]"><Sidebar /><section className="flex-1 px-6 py-8 md:px-10"><div className="mx-auto max-w-3xl"><div className="flex items-center justify-between"><Link href={`/workspaces/${workspaceId}/meetings`} className="text-sm text-[#787774]">← Meetings</Link><button onClick={save} disabled={saving} className="rounded-md bg-[#252525] px-3 py-1.5 text-sm text-white">{saving ? "Saving…" : "Save"}</button></div>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<input aria-label="Meeting title" value={title} onChange={(event) => setTitle(event.target.value)} className="mt-10 w-full bg-transparent text-4xl font-semibold tracking-[-0.03em] outline-none" /><section className="mt-10 rounded-md border border-black/[0.1] bg-white p-4"><div className="flex items-center justify-between"><div><h2 className="font-medium">Transcript</h2><p className="mt-1 text-sm text-[#787774]">Upload a recording when a server-side transcription provider is configured.</p></div><button onClick={copyTranscript} className="rounded-md border border-black/[0.12] px-2 py-1 text-sm">Copy transcript</button></div><input ref={fileInput} aria-label="Upload recording" type="file" accept="audio/*,video/*" className="sr-only" onChange={(event) => setFileName(event.target.files?.[0]?.name || "")} /><div className="mt-4 flex items-center gap-2"><button onClick={() => fileInput.current?.click()} className="rounded-md border border-black/[0.12] px-3 py-1.5 text-sm">Upload recording</button><span className="text-xs text-[#787774]">{fileName || "No recording selected"}</span><button disabled className="rounded-md bg-[#e9e9e6] px-3 py-1.5 text-sm text-[#787774]" title="Configure a server-side transcription provider to enable this">Transcribe</button></div><p className="mt-3 text-xs text-[#9b9a97]">Transcription is not configured in this deployment. No audio is uploaded or sent from this page.</p><textarea aria-label="Transcript" value={transcript} onChange={(event) => setTranscript(event.target.value)} placeholder="Paste or edit a transcript here…" className="mt-4 min-h-64 w-full resize-y rounded-md bg-[#fbfbfa] p-3 text-sm outline-none" /></section><section className="mt-5 rounded-md border border-black/[0.1] bg-white p-4"><h2 className="font-medium">Meeting notes</h2><p className="mt-1 text-sm text-[#787774]">Add a summary, decisions, and action items.</p><textarea aria-label="Meeting notes" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Summary\n\nKey decisions\n\nAction items" className="mt-4 min-h-48 w-full resize-y rounded-md bg-[#fbfbfa] p-3 text-sm outline-none" /></section><Comments workspaceId={workspaceId} entityType="meeting" entityId={meetingId} /></div></section></main>;
}
