"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { collection, onSnapshot, query, where } from "firebase/firestore";
import { useParams, useRouter } from "next/navigation";
import Sidebar from "@/components/sidebar";
import { useAuth } from "@/components/auth-provider";
import { db } from "@/lib/firebase";

type Task = { id: string; title: string; status: string; priority: string; dueDate?: Date };
type Meeting = { id: string; title: string; updatedAt?: Date };

export default function DashboardPage() {
  const { workspaceId } = useParams<{ workspaceId: string }>(); const router = useRouter(); const { firebaseUser, profile, loading } = useAuth(); const [tasks, setTasks] = useState<Task[]>([]); const [meetings, setMeetings] = useState<Meeting[]>([]); const [error, setError] = useState("");
  useEffect(() => { if (!loading && !firebaseUser) router.replace("/login"); }, [loading, firebaseUser, router]);
  useEffect(() => { if (!firebaseUser || !profile) return; return onSnapshot(query(collection(db, "tasks"), where("workspaceId", "==", workspaceId)), (snapshot) => setTasks(snapshot.docs.map((item) => ({ id: item.id, title: item.data().title || "Untitled task", status: item.data().status || "todo", priority: item.data().priority || "medium", dueDate: item.data().dueDate?.toDate() })).filter((task, index) => snapshot.docs[index].data().archived !== true)), (listenerError) => { console.error("Failed to load dashboard tasks:", listenerError); setError("Dashboard data could not be loaded."); }); }, [firebaseUser, profile, workspaceId]);
  useEffect(() => { if (!firebaseUser || !profile) return; return onSnapshot(query(collection(db, "meetings"), where("workspaceId", "==", workspaceId)), (snapshot) => setMeetings(snapshot.docs.map((item) => ({ id: item.id, title: item.data().title || "Untitled meeting", updatedAt: item.data().updatedAt?.toDate() }))), (listenerError) => { console.error("Failed to load dashboard meetings:", listenerError); setError("Dashboard data could not be loaded."); }); }, [firebaseUser, profile, workspaceId]);
  const counts = useMemo(() => ({ total: tasks.length, active: tasks.filter((task) => task.status === "in_progress").length, done: tasks.filter((task) => task.status === "done").length, urgent: tasks.filter((task) => task.priority === "urgent" || task.priority === "high").length }), [tasks]);
  if (loading) return <main className="grid min-h-screen place-items-center">Loading…</main>; if (!firebaseUser || !profile) return null;
  return <main className="flex min-h-screen bg-[#fbfbfa]"><Sidebar /><section className="flex-1 px-6 py-8 md:px-10"><div className="mx-auto max-w-6xl"><Link href={`/workspaces/${workspaceId}`} className="text-sm text-[#787774]">← Back to workspace</Link><div className="mt-8"><p className="text-xs font-medium text-[#9b9a97]">WORKSPACE VIEW</p><h1 className="mt-1 text-4xl font-semibold tracking-[-0.03em]">Dashboard</h1><p className="mt-2 text-sm text-[#787774]">A live overview of the work already in this workspace.</p></div>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="All tasks" value={counts.total} /><Metric label="In progress" value={counts.active} /><Metric label="Completed" value={counts.done} /><Metric label="High priority" value={counts.urgent} /></div><div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="rounded-md border border-black/[0.1] bg-white"><div className="flex items-center justify-between border-b border-black/[0.08] px-4 py-3"><h2 className="text-sm font-medium">Open tasks</h2><Link href={`/workspaces/${workspaceId}/tasks`} className="text-xs text-[#787774]">Open tasks →</Link></div>{tasks.filter((task) => task.status !== "done").slice(0, 6).map((task) => <div key={task.id} className="border-b border-black/[0.07] px-4 py-3 last:border-0"><p className="text-sm font-medium">{task.title}</p><p className="mt-1 text-xs capitalize text-[#787774]">{task.status.replace("_", " ")} · {task.priority}</p></div>)}{tasks.length === 0 && <p className="px-4 py-8 text-sm text-[#787774]">No tasks yet.</p>}</section><section className="rounded-md border border-black/[0.1] bg-white"><div className="flex items-center justify-between border-b border-black/[0.08] px-4 py-3"><h2 className="text-sm font-medium">Recent meetings</h2><Link href={`/workspaces/${workspaceId}/meetings`} className="text-xs text-[#787774]">Open meetings →</Link></div>{meetings.sort((a, b) => (b.updatedAt?.getTime() || 0) - (a.updatedAt?.getTime() || 0)).slice(0, 6).map((meeting) => <Link key={meeting.id} href={`/workspaces/${workspaceId}/meetings/${meeting.id}`} className="block border-b border-black/[0.07] px-4 py-3 last:border-0 hover:bg-[#f7f7f5]"><p className="text-sm font-medium">{meeting.title}</p><p className="mt-1 text-xs text-[#787774]">{meeting.updatedAt?.toLocaleString() || "New meeting"}</p></Link>)}{meetings.length === 0 && <p className="px-4 py-8 text-sm text-[#787774]">No meetings yet.</p>}</section></div></div></section></main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <section className="rounded-md border border-black/[0.1] bg-white p-4"><p className="text-xs text-[#787774]">{label}</p><p className="mt-2 text-3xl font-semibold tracking-[-0.03em]">{value}</p></section>; }
