"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { collection, onSnapshot, query, serverTimestamp, updateDoc, doc, where } from "firebase/firestore";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import Sidebar from "@/components/sidebar";
import NewTaskForm from "@/components/tasks/new-task-form";
import EditTaskForm, { EditableTask, EditableTaskStatus } from "@/components/tasks/edit-task-form";
import { useAuth } from "@/components/auth-provider";
import { db } from "@/lib/firebase";

const columns: { status: EditableTaskStatus; label: string }[] = [{ status: "todo", label: "Not started" }, { status: "in_progress", label: "In progress" }, { status: "blocked", label: "Blocked" }, { status: "done", label: "Done" }];

export default function TasksPage() {
  const { workspaceId } = useParams<{ workspaceId: string }>(); const router = useRouter(); const searchParams = useSearchParams(); const { firebaseUser, profile, loading: authLoading } = useAuth();
  const [tasks, setTasks] = useState<EditableTask[]>([]); const [view, setView] = useState<"table" | "board">("table"); const [creating, setCreating] = useState(false); const [error, setError] = useState(""); const [draggedId, setDraggedId] = useState<string | null>(null); const selected = tasks.find((task) => task.id === searchParams.get("task")) ?? null;
  useEffect(() => { if (!authLoading && !firebaseUser) router.replace("/login"); }, [authLoading, firebaseUser, router]);
  useEffect(() => { if (!firebaseUser || !profile || !workspaceId) return; return onSnapshot(query(collection(db, "tasks"), where("workspaceId", "==", workspaceId)), (snapshot) => setTasks(snapshot.docs.map((item) => { const value = item.data(); return { id: item.id, title: value.title || "Untitled task", description: value.description || "", workspaceId: value.workspaceId, status: value.status || "todo", priority: value.priority || "medium", assigneeId: value.assigneeId || null, dueDate: value.dueDate?.toDate(), createdBy: value.createdBy || "", createdAt: value.createdAt?.toDate(), updatedAt: value.updatedAt?.toDate() } as EditableTask; }).filter((task, index) => snapshot.docs[index].data().archived !== true)), (listenerError) => { console.error("Failed to listen for tasks:", listenerError); setError("Tasks could not be loaded."); }); }, [firebaseUser, profile, workspaceId]);
  async function moveTask(taskId: string, status: EditableTaskStatus) { const previous = tasks.find((task) => task.id === taskId); if (!previous || previous.status === status) return; setError(""); setTasks((current) => current.map((task) => task.id === taskId ? { ...task, status } : task)); try { await updateDoc(doc(db, "tasks", taskId), { status, updatedAt: serverTimestamp() }); } catch (moveError) { console.error("Failed to move task:", moveError); setTasks((current) => current.map((task) => task.id === taskId ? previous : task)); setError("Task status could not be saved. The change was reverted."); } }
  if (authLoading || (!profile && firebaseUser)) return <main className="grid min-h-screen place-items-center text-sm text-[#787774]">Loading tasks…</main>; if (!firebaseUser || !profile) return null;
  const openTask = (task: EditableTask) => router.push(`/workspaces/${workspaceId}/tasks?task=${task.id}`); const closeTask = () => router.push(`/workspaces/${workspaceId}/tasks`); return <main className="flex min-h-screen bg-[#fbfbfa]"><Sidebar /><section className="min-w-0 flex-1 px-6 py-8 md:px-10"><div className={`mx-auto ${selected ? "max-w-none" : "max-w-[1400px]"}`}><Link href={`/workspaces/${workspaceId}`} className="text-sm text-[#787774] hover:text-[#37352f]">← Back to workspace</Link><div className="mt-8 flex items-start justify-between"><div><p className="text-xs font-medium text-[#9b9a97]">TASKS</p><h1 className="mt-1 text-4xl font-semibold tracking-[-0.03em]">Tasks</h1></div><button onClick={() => setCreating(true)} className="rounded-md bg-[#252525] px-3 py-2 text-sm font-medium text-white">New task</button></div><div className="mt-8 flex border-b border-black/[0.1]"><button onClick={() => setView("table")} className="px-3 py-2 text-sm">▦ Table</button><button onClick={() => setView("board")} className="px-3 py-2 text-sm">▤ Board</button></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}{creating && <NewTaskForm workspaceId={workspaceId} currentUser={firebaseUser} onCancel={() => setCreating(false)} onCreated={() => setCreating(false)} />}<div className={selected ? "grid grid-cols-[minmax(0,1fr)_minmax(420px,48%)]" : ""}><div className="min-w-0">{view === "table" ? <TaskTable tasks={tasks} onOpen={openTask} onStatus={moveTask} /> : <TaskBoard tasks={tasks} draggedId={draggedId} setDraggedId={setDraggedId} onDrop={moveTask} onOpen={openTask} />}</div>{selected && <aside className="min-h-[calc(100vh-12rem)] border-l border-black/[0.1] bg-white px-5 py-4"><div className="flex justify-between"><button aria-label="Close task pane" onClick={closeTask} className="text-sm text-[#787774]">× Close</button><Link aria-label="Expand task" href={`/workspaces/${workspaceId}/tasks/${selected.id}`} className="text-sm text-[#787774]">↗ Expand</Link></div><EditTaskForm task={selected} onCancel={closeTask} onSaved={() => {}} onDeleted={closeTask} /></aside>}</div></div></section></main>;
}

function TaskTable({ tasks, onOpen, onStatus }: { tasks: EditableTask[]; onOpen: (task: EditableTask) => void; onStatus: (id: string, status: EditableTaskStatus) => void }) { return <div className="mt-4 overflow-x-auto rounded-md border border-black/[0.12] bg-white"><table className="w-full min-w-[760px] text-sm"><thead className="bg-[#fbfbfa] text-left text-xs text-[#787774]"><tr><th className="px-3 py-2">Task</th><th>Status</th><th>Priority</th><th>Due date</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id} className="border-t border-black/[0.08] hover:bg-[#f7f7f5]"><td><button className="w-full px-3 py-2 text-left font-medium" onClick={() => onOpen(task)}>{task.title}</button></td><td><select aria-label={`Status for ${task.title}`} value={task.status} onChange={(event) => onStatus(task.id, event.target.value as EditableTaskStatus)} className="rounded bg-transparent px-2 py-1"><option value="todo">Not started</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="done">Done</option></select></td><td className="capitalize text-[#787774]">{task.priority}</td><td className="text-[#787774]">{task.dueDate?.toLocaleDateString() || "—"}</td></tr>)}</tbody></table>{tasks.length === 0 && <p className="px-3 py-8 text-sm text-[#787774]">No tasks yet. Create one to get started.</p>}</div>; }
function TaskBoard({ tasks, draggedId, setDraggedId, onDrop, onOpen }: { tasks: EditableTask[]; draggedId: string | null; setDraggedId: (id: string | null) => void; onDrop: (id: string, status: EditableTaskStatus) => void; onOpen: (task: EditableTask) => void }) { return <div className="mt-5 flex gap-4 overflow-x-auto pb-4">{columns.map((column) => { const columnTasks = tasks.filter((task) => task.status === column.status); return <section aria-label={`${column.label} column`} key={column.status} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (draggedId) onDrop(draggedId, column.status); setDraggedId(null); }} className="w-72 shrink-0 rounded-md bg-[#f1f1ef] p-2"><header className="flex items-center justify-between px-1 py-2 text-sm font-medium"><span>{column.label}</span><span className="text-xs text-[#787774]">{columnTasks.length}</span></header><div className="min-h-32 space-y-2">{columnTasks.map((task) => <button key={task.id} draggable onDragStart={() => setDraggedId(task.id)} onClick={() => onOpen(task)} className="block w-full rounded-md border border-black/[0.1] bg-white p-3 text-left shadow-sm hover:bg-[#fbfbfa]"><p className="text-sm font-medium">{task.title}</p><p className="mt-2 text-xs capitalize text-[#787774]">{task.priority}{task.dueDate ? ` · due ${task.dueDate.toLocaleDateString()}` : ""}</p></button>)}</div></section>; })}</div>; }
