"use client";

import { useEffect, useId, useMemo, useRef, useState } from "react";
import { collection, onSnapshot, query, where } from "firebase/firestore";
import { useAuth } from "@/components/auth-provider";
import { authenticatedRequest } from "@/lib/authenticated-request";
import { db } from "@/lib/firebase";
import { getMembershipsForWorkspace } from "@/lib/memberships";
import { eligibleWorkspaceUsers } from "@/lib/meetings";
import { getUsers } from "@/lib/users";

type EntityType = "meeting" | "task" | "document" | "database-row";
type Mention = { uid: string; name: string; employeeId?: string };
type Comment = { id: string; body: string; authorUid: string; authorName: string; parentCommentId: string | null; mentionedUserIds: string[]; mentions: Mention[]; createdAt?: Date; editedAt?: Date; deletedAt?: Date };
const MAX_COMMENT_LENGTH = 4000;

function compactTimestamp(value?: Date) {
  if (!value) return "Just now";
  return new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(value);
}

function toComment(id: string, data: Record<string, unknown>): Comment {
  const mentions = Array.isArray(data.mentionSnapshots) ? data.mentionSnapshots.flatMap((value) => value && typeof value === "object" && typeof (value as Mention).uid === "string" && typeof (value as Mention).name === "string" ? [value as Mention] : []) : [];
  const date = (value: unknown) => value && typeof value === "object" && "toDate" in value ? (value as { toDate(): Date }).toDate() : undefined;
  return { id, body: typeof data.body === "string" ? data.body : "", authorUid: typeof data.authorUid === "string" ? data.authorUid : "", authorName: typeof data.authorName === "string" ? data.authorName : "Employee", parentCommentId: typeof data.parentCommentId === "string" ? data.parentCommentId : null, mentionedUserIds: Array.isArray(data.mentionedUserIds) ? data.mentionedUserIds.filter((id): id is string => typeof id === "string") : [], mentions, createdAt: date(data.createdAt), editedAt: date(data.editedAt), deletedAt: date(data.deletedAt) };
}

export function Comments({ workspaceId, entityType, entityId }: { workspaceId: string; entityType: EntityType; entityId: string }) {
  const { firebaseUser } = useAuth();
  const [comments, setComments] = useState<Comment[]>([]); const [people, setPeople] = useState<Mention[]>([]); const [body, setBody] = useState(""); const [mentionIds, setMentionIds] = useState<string[]>([]); const [replyTo, setReplyTo] = useState<Comment | null>(null); const [error, setError] = useState(""); const [posting, setPosting] = useState(false);
  useEffect(() => { if (!firebaseUser) return; return onSnapshot(query(collection(db, "comments"), where("workspaceId", "==", workspaceId), where("entityType", "==", entityType), where("entityId", "==", entityId)), (snapshot) => setComments(snapshot.docs.map((item) => toComment(item.id, item.data())).sort((a, b) => (a.createdAt?.getTime() || 0) - (b.createdAt?.getTime() || 0))), () => setError("Comments could not be loaded.")); }, [entityId, entityType, firebaseUser, workspaceId]);
  useEffect(() => { let live = true; void Promise.all([getUsers(), workspaceId === "company" ? Promise.resolve([]) : getMembershipsForWorkspace(workspaceId)]).then(([users, memberships]) => { if (live) setPeople(eligibleWorkspaceUsers(users, workspaceId, new Set(memberships.map((item) => item.userId))).map((user) => ({ uid: user.uid, name: user.name, employeeId: user.employeeId }))); }).catch(() => { if (live) setPeople([]); }); return () => { live = false; }; }, [workspaceId]);
  const roots = useMemo(() => comments.filter((item) => !item.parentCommentId), [comments]);
  const replyMap = useMemo(() => new Map(roots.map((item) => [item.id, comments.filter((comment) => comment.parentCommentId === item.id)])), [comments, roots]);
  async function send() { if (!firebaseUser || !body.trim() || posting) return; const activeMentions = people.filter((person) => mentionIds.includes(person.uid) && body.includes(`@${person.name}`)).map((person) => person.uid); setPosting(true); setError(""); try { const response = await authenticatedRequest(firebaseUser, `/api/workspaces/${workspaceId}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ entityType, entityId, body: body.trim(), parentCommentId: replyTo?.id, mentionedUserIds: activeMentions }) }); if (!response.ok) throw new Error(); setBody(""); setMentionIds([]); setReplyTo(null); } catch { setError("Comment could not be posted."); } finally { setPosting(false); } }
  async function edit(comment: Comment, text: string, mentionedUserIds: string[]) { if (!firebaseUser || !text) return false; const response = await authenticatedRequest(firebaseUser, `/api/workspaces/${workspaceId}/comments/${comment.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: text, mentionedUserIds }) }); if (!response.ok) { setError("Comment could not be updated."); return false; } setError(""); return true; }
  async function remove(comment: Comment) { if (!firebaseUser) return; const response = await authenticatedRequest(firebaseUser, `/api/workspaces/${workspaceId}/comments/${comment.id}`, { method: "DELETE" }); if (!response.ok) setError("Comment could not be deleted."); }
  return <section className="mt-9 border-t border-[var(--border)] pt-6"><div className="flex items-baseline justify-between"><h2 className="proveit-section-title">Activity &amp; comments</h2><span className="text-xs text-[var(--subtle)]">{comments.length || "No"} {comments.length === 1 ? "comment" : "comments"}</span></div>{roots.length ? <div className="mt-5 divide-y divide-[var(--border)]">{roots.map((comment) => <CommentItem key={comment.id} comment={comment} replies={replyMap.get(comment.id) || []} people={people} currentUid={firebaseUser?.uid} onReply={setReplyTo} onEdit={edit} onDelete={remove} />)}</div> : <p className="mt-4 text-sm text-[var(--muted)]">No comments yet. Start the conversation.</p>}<Composer body={body} setBody={setBody} people={people} mentionIds={mentionIds} setMentionIds={setMentionIds} replyTo={replyTo} onCancel={() => setReplyTo(null)} onSend={() => void send()} posting={posting} />{error ? <p role="alert" className="mt-2 text-sm text-[var(--danger)]">{error}</p> : null}</section>;
}

function Composer({ body, setBody, people, mentionIds, setMentionIds, replyTo, onCancel, onSend, posting }: { body: string; setBody(value: string): void; people: Mention[]; mentionIds: string[]; setMentionIds(value: string[]): void; replyTo: Comment | null; onCancel(): void; onSend(): void; posting: boolean }) {
  const ref = useRef<HTMLTextAreaElement>(null); const listboxId = useId(); const [search, setSearch] = useState<string | null>(null); const [active, setActive] = useState(0); const matches = search === null ? [] : people.filter((person) => person.name.toLowerCase().includes(search.toLowerCase())).slice(0, 6);
  function change(value: string, cursor: number) { setBody(value); const found = /(^|\s)@([^\s@]*)$/.exec(value.slice(0, cursor)); setSearch(found ? found[2] : null); setActive(0); }
  function choose(person: Mention) { const cursor = ref.current?.selectionStart ?? body.length; const before = body.slice(0, cursor); const found = /(^|\s)@([^\s@]*)$/.exec(before); if (!found) return; const start = cursor - found[0].length + found[1].length; setBody(`${body.slice(0, start)}@${person.name} ${body.slice(cursor)}`); setMentionIds([...new Set([...mentionIds, person.uid])]); setSearch(null); requestAnimationFrame(() => { const position = start + person.name.length + 2; ref.current?.focus(); ref.current?.setSelectionRange(position, position); }); }
  return <div className="mt-6 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3 shadow-[var(--shadow-sm)]">{replyTo ? <div className="mb-2 flex items-center justify-between gap-3 rounded-md bg-[var(--surface-muted)] px-3 py-2 text-xs"><span className="truncate">Replying to {replyTo.authorName}</span><button type="button" className="min-h-9 shrink-0 text-[var(--secondary)]" onClick={onCancel}>Cancel</button></div> : null}<div className="relative"><textarea ref={ref} role="combobox" aria-autocomplete="list" aria-expanded={search !== null} aria-controls={search !== null ? listboxId : undefined} aria-activedescendant={search !== null && matches[active] ? `${listboxId}-${matches[active].uid}` : undefined} aria-label="Write a comment" maxLength={MAX_COMMENT_LENGTH} value={body} onChange={(event) => change(event.target.value, event.target.selectionStart)} onKeyDown={(event) => { if (event.key === "Escape") setSearch(null); if (matches.length && event.key === "ArrowDown") { event.preventDefault(); setActive((value) => (value + 1) % matches.length); } if (matches.length && event.key === "ArrowUp") { event.preventDefault(); setActive((value) => (value - 1 + matches.length) % matches.length); } if (matches.length && event.key === "Enter" && search !== null) { event.preventDefault(); choose(matches[active]); } }} placeholder="Write a comment… Type @ to mention someone." className="min-h-24 w-full resize-y rounded-lg border border-transparent bg-[var(--sidebar)] px-3 py-2.5 text-sm leading-6 outline-none placeholder:text-[var(--subtle)] focus:border-[var(--focus)] focus:ring-2 focus:ring-[var(--focus)]/20" />{search !== null && <MentionOptions id={listboxId} matches={matches} active={active} onChoose={choose} label="Mention suggestions" />}</div><div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-[var(--subtle)]">{body.length}/{MAX_COMMENT_LENGTH}</span><button data-testid="comment-submit" type="button" onClick={onSend} disabled={!body.trim() || posting} className="proveit-primary-button disabled:opacity-50">{posting ? "Sending…" : replyTo ? "Send reply" : "Send comment"}</button></div></div>;
}

function MentionOptions({ id, matches, active, onChoose, label }: { id: string; matches: Mention[]; active: number; onChoose(person: Mention): void; label: string }) {
  return <div id={id} role="listbox" aria-label={label} className="absolute bottom-full left-0 z-10 mb-2 w-full max-w-sm rounded-lg border border-[var(--border)] bg-[var(--surface-elevated)] p-1 shadow-[var(--shadow-md)]">{matches.length ? matches.map((person, index) => <button id={`${id}-${person.uid}`} role="option" aria-selected={index === active} type="button" key={person.uid} onClick={() => onChoose(person)} className={`block min-h-11 w-full rounded-md px-3 py-2 text-left hover:bg-[var(--hover)] ${index === active ? "bg-[var(--info-soft)]" : ""}`}><span className="block text-sm">@{person.name}</span>{person.employeeId ? <span className="block text-xs text-[var(--muted)]">Employee ID · {person.employeeId}</span> : null}</button>) : <p className="px-3 py-2 text-sm text-[var(--muted)]">No matching workspace members.</p>}</div>;
}

function EditComment({ comment, people, onSave, onCancel }: { comment: Comment; people: Mention[]; onSave(text: string, mentionedUserIds: string[]): Promise<boolean>; onCancel(): void }) {
  const ref = useRef<HTMLTextAreaElement>(null); const listboxId = useId(); const [text, setText] = useState(comment.body); const [mentionIds, setMentionIds] = useState(comment.mentionedUserIds); const [search, setSearch] = useState<string | null>(null); const [active, setActive] = useState(0); const [saving, setSaving] = useState(false); const matches = search === null ? [] : people.filter((person) => person.name.toLowerCase().includes(search.toLowerCase())).slice(0, 6);
  function change(value: string, cursor: number) { setText(value); const found = /(^|\s)@([^\s@]*)$/.exec(value.slice(0, cursor)); setSearch(found ? found[2] : null); setActive(0); }
  function choose(person: Mention) { const cursor = ref.current?.selectionStart ?? text.length; const before = text.slice(0, cursor); const found = /(^|\s)@([^\s@]*)$/.exec(before); if (!found) return; const start = cursor - found[0].length + found[1].length; setText(`${text.slice(0, start)}@${person.name} ${text.slice(cursor)}`); setMentionIds((current) => [...new Set([...current, person.uid])]); setSearch(null); requestAnimationFrame(() => { const position = start + person.name.length + 2; ref.current?.focus(); ref.current?.setSelectionRange(position, position); }); }
  const activeMentionIds = people.filter((person) => mentionIds.includes(person.uid) && text.includes(`@${person.name}`)).map((person) => person.uid);
  return <div className="relative mt-2"><textarea ref={ref} autoFocus role="combobox" aria-autocomplete="list" aria-expanded={search !== null} aria-controls={search !== null ? listboxId : undefined} aria-activedescendant={search !== null && matches[active] ? `${listboxId}-${matches[active].uid}` : undefined} aria-label="Edit comment" maxLength={MAX_COMMENT_LENGTH} value={text} onChange={(event) => change(event.target.value, event.target.selectionStart)} onKeyDown={(event) => { if (event.key === "Escape") { if (search !== null) setSearch(null); else onCancel(); } if (matches.length && event.key === "ArrowDown") { event.preventDefault(); setActive((value) => (value + 1) % matches.length); } if (matches.length && event.key === "ArrowUp") { event.preventDefault(); setActive((value) => (value - 1 + matches.length) % matches.length); } if (matches.length && event.key === "Enter" && search !== null) { event.preventDefault(); choose(matches[active]); } }} className="proveit-control min-h-20 w-full px-3 py-2" />{search !== null && <MentionOptions id={listboxId} matches={matches} active={active} onChoose={choose} label="Edit mention suggestions" />}<div className="mt-2 flex gap-3 text-xs"><button type="button" className="min-h-9 text-[var(--secondary)]" disabled={!text.trim() || saving} onClick={() => { setSaving(true); Promise.resolve(onSave(text.trim(), activeMentionIds)).finally(() => setSaving(false)); }}>{saving ? "Saving…" : "Save"}</button><button type="button" className="min-h-9" disabled={saving} onClick={onCancel}>Cancel</button></div></div>;
}

function CommentItem({ comment, replies, people, currentUid, onReply, onEdit, onDelete, nested = false }: { comment: Comment; replies: Comment[]; people: Mention[]; currentUid?: string; onReply(comment: Comment): void; onEdit(comment: Comment, text: string, mentionedUserIds: string[]): Promise<boolean>; onDelete(comment: Comment): Promise<void>; nested?: boolean }) {
  const [editing, setEditing] = useState(false); const [confirming, setConfirming] = useState(false); const own = comment.authorUid === currentUid;
  return <article className={nested ? "ml-3 border-l border-[var(--border)] pl-3 sm:ml-8 sm:pl-4" : ""}><div className="flex gap-3 py-4"><span aria-hidden className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[var(--info-soft)] text-xs font-semibold text-[var(--info)]">{comment.authorName.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline gap-x-2 gap-y-0.5"><p className="text-sm font-medium">{comment.authorName}</p><time dateTime={comment.createdAt?.toISOString()} className="text-xs text-[var(--subtle)]">{compactTimestamp(comment.createdAt)}</time>{comment.editedAt ? <span className="text-xs text-[var(--subtle)]">Edited</span> : null}</div>{comment.deletedAt ? <p className="mt-1 text-sm italic text-[var(--muted)]">Comment deleted.</p> : editing ? <EditComment comment={comment} people={people} onSave={async (text, mentionedUserIds) => { const saved = await onEdit(comment, text, mentionedUserIds); if (saved) setEditing(false); return saved; }} onCancel={() => setEditing(false)} /> : <Body comment={comment} />} {!comment.deletedAt && <div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-2 text-xs">{!nested && <button type="button" className="min-h-8 text-[var(--secondary)]" onClick={() => onReply(comment)}>Reply</button>}{own && !editing && (confirming ? <><span className="basis-full text-[var(--muted)] sm:basis-auto">Replies will be preserved.</span><button type="button" className="min-h-8 text-[var(--danger)]" onClick={() => void onDelete(comment)}>Confirm delete</button><button type="button" className="min-h-8" onClick={() => setConfirming(false)}>Cancel</button></> : <><button type="button" className="min-h-8" onClick={() => setEditing(true)}>Edit</button><button type="button" className="min-h-8" onClick={() => setConfirming(true)}>Delete</button></>)}</div>}</div></div>{!nested && replies.map((reply) => <CommentItem key={reply.id} comment={reply} replies={[]} people={people} currentUid={currentUid} onReply={onReply} onEdit={onEdit} onDelete={onDelete} nested />)}</article>;
}

function Body({ comment }: { comment: Comment }) {
  const mentions = new Map(comment.mentions.map((mention) => [`@${mention.name}`, mention]));
  if (!mentions.size) return <p className="mt-1 whitespace-pre-wrap text-sm leading-6">{comment.body}</p>;
  const pattern = [...mentions.keys()].sort((a, b) => b.length - a.length).map((value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|");
  return <p className="mt-1 whitespace-pre-wrap text-sm leading-6">{comment.body.split(new RegExp(`(${pattern})`, "g")).map((part, index) => mentions.has(part) ? <span key={`${mentions.get(part)!.uid}-${index}`} className="rounded bg-[var(--info-soft)] px-1 font-medium text-[var(--info)]">{part}</span> : part)}</p>;
}
