"use client";

import { useEffect, useState } from "react";
import { collection, doc, onSnapshot, query, serverTimestamp, where, writeBatch } from "firebase/firestore";
import { useAuth } from "@/components/auth-provider";
import { db } from "@/lib/firebase";
import { authenticatedRequest } from "@/lib/authenticated-request";

type EntityType = "meeting" | "task" | "document" | "database-row";
type Comment = { id: string; body: string; authorUid: string; authorName: string; createdAt?: Date; editedAt?: Date };
const MAX_COMMENT_LENGTH = 4000;

export function Comments({ workspaceId, entityType, entityId }: { workspaceId: string; entityType: EntityType; entityId: string }) {
  const { firebaseUser, profile } = useAuth();
  const [comments, setComments] = useState<Comment[]>([]); const [body, setBody] = useState(""); const [error, setError] = useState(""); const [posting, setPosting] = useState(false);
  useEffect(() => { if (!firebaseUser) return; return onSnapshot(query(collection(db, "comments"), where("workspaceId", "==", workspaceId), where("entityId", "==", entityId)), (snapshot) => setComments(snapshot.docs.map((item) => ({ id: item.id, body: item.data().body || "", authorUid: item.data().authorUid || "", authorName: item.data().authorName || "Employee", createdAt: item.data().createdAt?.toDate(), editedAt: item.data().editedAt?.toDate() })).sort((left, right) => (left.createdAt?.getTime() || 0) - (right.createdAt?.getTime() || 0))), () => setError("Comments could not be loaded.")); }, [entityId, firebaseUser, workspaceId]);
  async function post() { const text = body.trim(); if (!firebaseUser || !profile || !text || text.length > MAX_COMMENT_LENGTH || posting) return; setPosting(true); setError(""); try { if (entityType === "task") { const response = await authenticatedRequest(firebaseUser, `/api/tasks/${entityId}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: text }) }); if (!response.ok) throw new Error("comment"); } else { const batch = writeBatch(db); batch.set(doc(collection(db, "comments")), { workspaceId, entityType, entityId, body: text, authorUid: firebaseUser.uid, authorName: profile.name, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); await batch.commit(); } setBody(""); } catch { setError("Comment could not be posted."); } finally { setPosting(false); } }
  async function edit(comment: Comment, text: string) { if (!firebaseUser || entityType !== "task") return; const response = await authenticatedRequest(firebaseUser, `/api/tasks/${entityId}/comments/${comment.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: text }) }); if (!response.ok) setError("Comment could not be updated."); }
  async function remove(comment: Comment) { if (!firebaseUser || entityType !== "task") return; const response = await authenticatedRequest(firebaseUser, `/api/tasks/${entityId}/comments/${comment.id}`, { method: "DELETE" }); if (!response.ok) setError("Comment could not be deleted."); }
  return <section className="mt-9 border-t border-[var(--border)] pt-6"><div className="flex items-baseline justify-between"><h2 className="proveit-section-title">Activity &amp; comments</h2><span className="text-xs text-[var(--subtle)]">{comments.length || "No"} {comments.length === 1 ? "comment" : "comments"}</span></div>{!comments.length && !error ? <p className="mt-4 text-sm text-[var(--muted)]">No comments yet. Start the conversation about this task.</p> : <div className="mt-5 divide-y divide-[var(--border)]">{comments.map((comment) => <CommentItem key={comment.id} comment={comment} editable={entityType === "task" && comment.authorUid === firebaseUser?.uid} onEdit={edit} onDelete={remove} />)}</div>}<div className="mt-6 flex gap-3 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3 shadow-[var(--shadow-sm)]"><span aria-hidden className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[var(--active)] text-xs font-semibold">{profile?.name?.slice(0, 2).toUpperCase() || "ME"}</span><div className="min-w-0 flex-1"><textarea aria-label="Write a comment" maxLength={MAX_COMMENT_LENGTH} value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write a comment…" className="min-h-24 w-full resize-y rounded-lg border border-transparent bg-[var(--sidebar)] px-3 py-2.5 text-sm leading-6 outline-none placeholder:text-[var(--subtle)] focus:border-[var(--focus)]" /><div className="mt-3 flex items-center justify-between"><span className="text-xs text-[var(--subtle)]">{body.length}/{MAX_COMMENT_LENGTH}</span><button data-testid="comment-submit" onClick={() => void post()} disabled={!body.trim() || posting} className="proveit-primary-button disabled:cursor-not-allowed disabled:opacity-50">{posting ? "Sending…" : "Send comment"}</button></div></div></div>{error ? <p role="alert" className="mt-2 text-sm text-[var(--danger)]">{error}</p> : null}</section>;
}

function CommentItem({ comment, editable, onEdit, onDelete }: { comment: Comment; editable: boolean; onEdit: (comment: Comment, text: string) => Promise<void>; onDelete: (comment: Comment) => Promise<void> }) {
  const [editing, setEditing] = useState(false); const [text, setText] = useState(comment.body); const [confirming, setConfirming] = useState(false);
  return <article className="flex gap-3 py-4"><span aria-hidden className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[var(--active)] text-xs font-semibold">{comment.authorName.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline gap-x-2"><p className="text-sm font-medium">{comment.authorName}</p><time className="text-xs text-[var(--subtle)]">{comment.createdAt?.toLocaleString() || "Just now"}</time>{comment.editedAt ? <span className="text-xs text-[var(--subtle)]">Edited</span> : null}</div>{editing ? <><textarea aria-label="Edit comment" value={text} maxLength={MAX_COMMENT_LENGTH} onChange={(event) => setText(event.target.value)} className="proveit-control mt-2 min-h-20 w-full px-3 py-2" /><div className="mt-2 flex gap-2"><button className="text-xs text-[var(--secondary)]" onClick={() => { void onEdit(comment, text.trim()); setEditing(false); }}>Save</button><button className="text-xs text-[var(--muted)]" onClick={() => { setText(comment.body); setEditing(false); }}>Cancel</button></div></> : <p className="mt-1 whitespace-pre-wrap text-sm leading-6">{comment.body}</p>}{editable && !editing ? <div className="mt-2 flex gap-3 text-xs">{confirming ? <><span>Delete this comment?</span><button className="text-[var(--danger)]" onClick={() => void onDelete(comment)}>Delete</button><button className="text-[var(--muted)]" onClick={() => setConfirming(false)}>Cancel</button></> : <><button className="text-[var(--secondary)]" onClick={() => setEditing(true)}>Edit</button><button className="text-[var(--muted)]" onClick={() => setConfirming(true)}>Delete</button></>}</div> : null}</div></article>;
}
