"use client";

import { useEffect, useState } from "react";
import { collection, doc, getDoc, onSnapshot, query, serverTimestamp, where, writeBatch } from "firebase/firestore";
import { useAuth } from "@/components/auth-provider";
import { db } from "@/lib/firebase";
import { getUsers } from "@/lib/users";
import { ProveItUser } from "@/types/user";

type EntityType = "meeting" | "task" | "document" | "database-row";
type Comment = { id: string; body: string; authorUid: string; authorName: string; createdAt?: Date; parentCommentId?: string | null };

export function Comments({ workspaceId, entityType, entityId }: { workspaceId: string; entityType: EntityType; entityId: string }) {
  const { firebaseUser, profile } = useAuth();
  const [comments, setComments] = useState<Comment[]>([]); const [users, setUsers] = useState<ProveItUser[]>([]); const [body, setBody] = useState(""); const [mention, setMention] = useState(""); const [replyingTo, setReplyingTo] = useState<Comment | null>(null); const [error, setError] = useState(""); const [posting, setPosting] = useState(false);
  useEffect(() => { if (!firebaseUser) return; getUsers().then(setUsers).catch(() => setError("People could not be loaded.")); return onSnapshot(query(collection(db, "comments"), where("workspaceId", "==", workspaceId), where("entityId", "==", entityId)), (snapshot) => setComments(snapshot.docs.map((item) => ({ id: item.id, body: item.data().body || "", authorUid: item.data().authorUid || "", authorName: item.data().authorName || "Unknown employee", parentCommentId: item.data().parentCommentId || null, createdAt: item.data().createdAt?.toDate() })).sort((a, b) => (a.createdAt?.getTime() || 0) - (b.createdAt?.getTime() || 0))), () => setError("Comments could not be loaded.")); }, [firebaseUser, entityId, workspaceId]);
  async function postComment() { if (!firebaseUser || !profile || !body.trim() || posting) return; const mentioned = users.find((user) => user.uid === mention); try { setPosting(true); const batch = writeBatch(db); batch.set(doc(collection(db, "comments")), { workspaceId, entityType, entityId, body: body.trim(), authorUid: firebaseUser.uid, authorName: profile.name, mentionedUid: mentioned?.uid || null, parentCommentId: replyingTo?.id || null, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); const recipients = new Set<string>(); if (mentioned && mentioned.uid !== firebaseUser.uid && (await getDoc(doc(db, "users", mentioned.uid))).data()?.notificationPreferences?.mentions !== false) recipients.add(mentioned.uid); if (replyingTo && replyingTo.authorUid !== firebaseUser.uid) recipients.add(replyingTo.authorUid); recipients.forEach((recipientUid) => batch.set(doc(collection(db, "notifications")), { recipientUid, workspaceId, type: mentioned?.uid === recipientUid ? "mention" : "comment_reply", title: mentioned?.uid === recipientUid ? "You were mentioned" : "New reply", message: `${profile.name} ${mentioned?.uid === recipientUid ? "mentioned you" : "replied to your comment"}.`, entityType, entityId, actorUid: firebaseUser.uid, createdAt: serverTimestamp(), readAt: null, archivedAt: null })); await batch.commit(); setBody(""); setMention(""); setReplyingTo(null); } catch (postError) { console.error("Failed to post comment:", postError); setError("Comment could not be posted."); } finally { setPosting(false); } }
  const roots = comments.filter((comment) => !comment.parentCommentId);
  return <section className="mt-8 border-t border-black/[0.08] pt-5"><h2 className="text-base font-medium">Comments</h2><div className="mt-4 space-y-5">{roots.map((comment) => <Thread key={comment.id} comment={comment} replies={comments.filter((reply) => reply.parentCommentId === comment.id)} onReply={setReplyingTo} />)}</div><div className="mt-5 border-t border-black/[0.08] pt-4">{replyingTo && <p className="mb-2 text-xs text-[#787774]">Replying to {replyingTo.authorName} <button onClick={() => setReplyingTo(null)} className="underline">Cancel</button></p>}<textarea aria-label="Comment" value={body} onChange={(event) => setBody(event.target.value)} placeholder={replyingTo ? "Write a reply…" : "Add a comment…"} className="min-h-20 w-full resize-y bg-transparent py-2 text-sm outline-none placeholder:text-[#9b9a97]" /><div className="flex items-center justify-between gap-3"><select aria-label="Mention teammate" value={mention} onChange={(event) => setMention(event.target.value)} className="rounded-md bg-[#f1f1ef] px-2 py-1.5 text-sm"><option value="">Mention someone…</option>{users.filter((user) => user.active && user.uid !== firebaseUser?.uid).map((user) => <option key={user.uid} value={user.uid}>@{user.name}</option>)}</select><button onClick={postComment} disabled={!body.trim() || posting} className="rounded-md bg-[#252525] px-3 py-1.5 text-sm text-white disabled:opacity-50">{posting ? "Posting…" : replyingTo ? "Reply" : "Comment"}</button></div>{error && <p role="alert" className="mt-2 text-sm text-red-700">{error}</p>}</div></section>;
}

function Thread({ comment, replies, onReply }: { comment: Comment; replies: Comment[]; onReply: (comment: Comment) => void }) { const [show, setShow] = useState(true); return <article><CommentItem comment={comment} onReply={onReply} />{replies.length > 0 && <div className="ml-5 mt-3 border-l border-black/[0.1] pl-4"><button onClick={() => setShow(!show)} className="mb-2 text-xs text-[#787774]">{show ? "Hide" : "Show"} {replies.length} {replies.length === 1 ? "reply" : "replies"}</button>{show && replies.map((reply) => <CommentItem key={reply.id} comment={reply} onReply={onReply} />)}</div>}</article>; }
function CommentItem({ comment, onReply }: { comment: Comment; onReply: (comment: Comment) => void }) { return <div className="group flex gap-2 py-1"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[#e9e9e6] text-[10px] text-[#787774]">{comment.authorName.slice(0, 1).toUpperCase()}</span><div><p className="text-sm"><span className="font-medium">{comment.authorName}</span><span className="ml-1 text-xs text-[#9b9a97]">{comment.createdAt?.toLocaleString() || "Just now"}</span></p><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{comment.body}</p><button onClick={() => onReply(comment)} className="mt-1 text-xs text-[#787774] opacity-0 group-hover:opacity-100 focus:opacity-100">Reply</button></div></div>; }
